FROM oven/bun:1.3.8

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/backend/package.json apps/backend/
COPY apps/web/package.json apps/web/
COPY packages/auth/package.json packages/auth/
COPY packages/db/package.json packages/db/
COPY packages/image/package.json packages/image/
COPY packages/types/package.json packages/types/
COPY packages/typescript-config/package.json packages/typescript-config/
COPY packages/ui/package.json packages/ui/

RUN bun install

COPY . .

WORKDIR /app/apps/web
EXPOSE 3001

CMD ["bun", "run", "dev", "--host"]
